
services:
  api:
    container_name: barber-shop_service
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pnpm start:dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - ./prisma/:/usr/src/app/prisma
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    networks:
      - electronic-invoice-n


networks:
  electronic-invoice-n:
    driver: bridge

    

