FROM node:21.0.0-alpine3.18 AS builder

WORKDIR /usr/src/app
RUN npm i -g pnpm@8.6.0

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install 

COPY . .

RUN pnpm prisma:generate
CMD ["pnpm", "start:dev"]


